minVersion: 1.0.0
artifactProvider:
  name: none
statusProvider:
  name: github
  config:
    contexts:
      - 'vroom-build-docker-image-commit (sentryio)'
targets:
  - name: github
  - name: docker
    source: us.gcr.io/sentryio/vroom
    target: getsentry/vroom
