repos:
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.1
  hooks:
    - id: go-build
    - id: go-imports
    - id: go-mod-tidy
    - id: golangci-lint
    - id: no-go-testing
    - id: validate-toml
