name: authenticate-with-gcp
inputs:
  service_account_email:
    required: true
  service_account_key:
    required: true

runs:
  using: composite
  steps:
    - name: Authenticate with GCP
      shell: bash
      env:
        GCP_SERVICE_ACCOUNT_KEY : ${{ inputs.gcp_service_account_key }}
      run: |
        set -eou pipefail
        mkdir -p ~/.gcp
        key_path="${HOME}/.gcp/key.json"
        echo $GCP_SERVICE_ACCOUNT_KEY > "$key_path"
        gcloud auth activate-service-account "${{ inputs.gcp_service_account_email }}" --key-file="$key_path"
        gcloud config set project specto-dev
