format_version: 10
pipelines:
    deploy-vroom:
        environment_variables:
            GITHUB_TOKEN: "{{SECRET:[devinfra-github][token]}}"
            GCP_PROJECT: internal-sentry
            GKE_REGION:
            GKE_CLUSTER_ZONE:
            GKE_CLUSTER:
            ENVIRONMENT: production
        group: vroom
        lock_behavior: unlockWhenFinished
        materials:
            vroom_repo:
                git: git@github.com:getsentry/vroom.git
                shallow_clone: true
                destination: vroom
                branch: main
        stages:
            - checks:
                  fetch_materials: true
                  approval:
                      type: manual
                  jobs:
                      check_ci_status:
                          timeout: 600
                          elastic_profile_id: vroom
                          tasks:
                              - script: |
                                    /devinfra/scripts/checks/githubactions/checkruns.py \
                                        getsentry/vroom \
                                        ${GO_REVISION_VROOM_REPO} \
                                        test-vroom
                      check_build_status:
                          timeout: 600
                          elastic_profile_id: vroom
                          tasks:
                              - script: |
                                 /devinfra/scripts/checks/googlecloud/checkcloudbuild.py \
                                    ${GO_REVISION_VROOM_REPO} \
                                    ${GCP_PROJECT} \
                                    "us.gcr.io/${GCP_PROJECT}/vroom"
            - deploy:
                  approval:
                      type: manual
                      allow_only_on_success: true
                  jobs:
                      deploy-to-k8s:
                          timeout: 600
                          elastic_profile_id: vroom
                          tasks:
                              - script: |
                                   /devinfra/scripts/k8s/k8sdeploy.py \
                                      --context="gke_${GCP_PROJECT}_${GKE_REGION}-${GKE_CLUSTER_ZONE}_${GKE_CLUSTER}" \
                                      --label-selector="service=vroom,component=default,environment=${ENVIRONMENT}" \
                                      --image="us.gcr.io/${GCP_PROJECT}/vroom:${GO_REVISION_VROOM_REPO}" \
                                      --container-name="vroom"
