name: continuous-integration

on:
  pull_request:
    branches:
      - '*'
    paths:
      - 'internal/**'
      - 'cmd/**'
      - 'pkg/**'
      - 'vendor/**'
      - '.github/workflows/ci.yml'
  push:
    branches:
      - main

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

env:
  SHELL: /bin/bash

defaults:
  run:
    shell: bash

jobs:
  test-vroom:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v3
      with:
        go-version: 'stable'
    - run: go install golang.org/x/tools/cmd/goimports@latest
    - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.51.1
    - uses: pre-commit/action@v3.0.0
    - run: make test
    - name: TruffleHog OSS
      uses: trufflesecurity/trufflehog@v3.16.4
      with:
        path: ./
        base: ${{ github.event.repository.default_branch }}
        head: HEAD
        extra_args: --debug --only-verified
