name: continuous-integration

on:
  pull_request:
    branches:
      - '*'
    paths:
      - 'internal/**'
      - 'cmd/**'
      - 'pkg/**'
      - 'vendor/**'
      - '.github/workflows/ci.yml'
  push:
    branches:
      - main

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

env:
  SHELL: /bin/bash

defaults:
  run:
    shell: bash

jobs:
  test-vroom:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v3
    - name: Install Golang
      run: curl -LO https://get.golang.org/$(uname)/go_installer && chmod +x go_installer && ./go_installer && rm go_installer
    - name: Install golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.51.1
    - name: Install goimports
      run: go install golang.org/x/tools/cmd/goimports@latest
    - uses: pre-commit/action@v3.0.0
    - name: Run golang tests
      run: make test

